---
- name: Create Argo Workflow for building garage-genie Docker image
  hosts: localhost
  gather_facts: false
  vars:
    image_name: "garage-genie"
    image_tag: "latest"
    registry: "10.0.0.248"
    argo_namespace: "argo"
    workflow_template: "{{ playbook_dir }}/templates/argo_workflow_build_garage_genie.yaml.j2"
    rendered_workflow: "/tmp/argo_workflow_build_garage_genie.yaml"
  tasks:
    - name: Render Argo Workflow manifest
      template:
        src: "{{ workflow_template }}"
        dest: "{{ rendered_workflow }}"
      vars:
        image_name: "{{ image_name }}"
        image_tag: "{{ image_tag }}"
        registry: "{{ registry }}"

    - name: Submit Argo Workflow
      command: >
        kubectl apply -n {{ argo_namespace }} -f {{ rendered_workflow }}
      register: argo_submit

    - name: Show Argo Workflow submission result
      debug:
        var: argo_submit.stdout
