---
- name: Install Docker Registry on k3s
  hosts: masters
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # === Install Docker Registry ===
    - include_tasks: templates/install_registry.yaml

  post_tasks:
    - name: Display registry access information
      debug:
        msg:
          - "==============================================="
          - "Docker Registry Installation Complete!"
          - "==============================================="
          - ""
          - "Registry Access Information:"
          - "  Internal URL: http://{{ registry_lb_ip }}:5000"
          - "  External URL: https://{{ registry_host }}"
          - "  Authentication: Disabled (open access)"
          - ""
          - "To use the registry:"
          - "  1. Tag image: docker tag my-image:latest {{ registry_lb_ip }}:5000/my-image:latest"
          - "  2. Push image: docker push {{ registry_lb_ip }}:5000/my-image:latest"
          - "  3. Pull image: docker pull {{ registry_lb_ip }}:5000/my-image:latest"
          - ""
          - "Note: Add '{{ registry_host }}' to your /etc/hosts file pointing to {{ registry_lb_ip }}"
          - "      for external URL access, or configure your DNS server."
          - "==============================================="
