- name: Configure k3s to use Pi-hole DNS
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "^DNS="
    line: "DNS={{ pihole_lb_ip }}"
    create: yes
  notify: restart systemd-resolved

- name: Configure coredns to use Pi-hole
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns
        namespace: kube-system
      data:
        Corefile: |
          .:53 {
              errors
              health {
                  lameduck 5s
              }
              ready
              kubernetes cluster.local in-addr.arpa ip6.arpa {
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
                  ttl 30
              }
              prometheus :9153
              forward . {{ pihole_lb_ip }}:{{ pihole_dns_port }}
              cache 30
              loop
              reload
              loadbalance
          }
