- name: Configure sysctl for k3s
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }
    - { name: "vm.overcommit_memory", value: "1" }
    - { name: "kernel.panic", value: "10" }
    - { name: "kernel.panic_on_oops", value: "1" }
