name: Ansible CI
on:
  push:
    branches: ["main", "feat/**"]
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint
          ansible-galaxy install -r requirements.yml
      - run: yamllint .
      - run: ansible-lint
      - run: ansible-playbook -i inventories/prod/hosts.ini playbooks/site.yml --syntax-check

